//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hayvanlar
    {
        public int HayvanID { get; set; }
        public string Tur { get; set; }
        public string Yas { get; set; }
        public string Kilo { get; set; }
        public string SağlıkDurumu { get; set; }
        public string AşıDurumu { get; set; }
        public string Adres { get; set; }
    }
}
