//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahalleler
    {
        public int MahalleID { get; set; }
        public string MahalleAdı { get; set; }
        public string YemekTürü { get; set; }
        public Nullable<int> YemekMiktarı_KG { get; set; }
    }
}
