//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projeEntities : DbContext
    {
        public projeEntities()
            : base("name=projeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adres> Adres { get; set; }
        public DbSet<Bildirimler> Bildirimler { get; set; }
        public DbSet<Hayvanlar> Hayvanlar { get; set; }
        public DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public DbSet<Mahalleler> Mahalleler { get; set; }
        public DbSet<Sehirler> Sehirler { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Veterinerler> Veterinerler { get; set; }
        public DbSet<Yemekler> Yemekler { get; set; }
        public DbSet<Yoneticiler> Yoneticiler { get; set; }
    }
}
