//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemekler
    {
        public int YemekID { get; set; }
        public string YemekTur { get; set; }
        public Nullable<int> YemekMiktar_KG_ { get; set; }
    }
}
